In [1]:
import pandas as pd
from sklearn.svm import SVC, LinearSVC
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


# np.random.seed(5)

dados = pd.read_csv("data/house_price/data.csv")
dados.head()
# a_renomear = {"expected_hours":"horas_esperadas", "price":"preco", "unfinished":"nao_finalizado"}
# dados.rename(columns=a_renomear, inplace=True)

# trocar = {0:1, 1:0}

# dados["finalizado"] = dados.nao_finalizado.map(trocar)

# sns.scatterplot(x="condition", y="price", data=dados)
dados["price"] = dados["price"].apply(int)
x = dados[["sqft_above","sqft_basement","sqft_living"]]
y = dados[["price"]]


treino_x, teste_x, treino_y, teste_y = train_test_split(x,y, test_size=0.25, random_state = 20)


modelo = LinearSVC()
modelo.fit(treino_x, treino_y)
# for i in treino_x.sqft_living:
#     if not isinstance(i,int):
#         print(i)
previsoes = modelo.predict(teste_x)

acuracia = accuracy_score(teste_y, previsoes)*100
previsoes
print("A acurácia foi de : %.2f%% " % acuracia )

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

A acurácia foi de : 0.00%

/usr/local/lib/python3.6/dist-packages/sklearn/svm/_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)

In [2]:
dados.head()

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,street,city,statezip,country
0,2014-05-02 00:00:00,313000,3.0,1.50,1340,7912,1.5,0,0,3,1340,0,1955,2005,18810 Densmore Ave N,Shoreline,WA 98133,USA
1,2014-05-02 00:00:00,2384000,5.0,2.50,3650,9050,2.0,0,4,5,3370,280,1921,0,709 W Blaine St,Seattle,WA 98119,USA
2,2014-05-02 00:00:00,342000,3.0,2.00,1930,11947,1.0,0,0,4,1930,0,1966,0,26206-26214 143rd Ave SE,Kent,WA 98042,USA
3,2014-05-02 00:00:00,420000,3.0,2.25,2000,8030,1.0,0,0,4,1000,1000,1963,0,857 170th Pl NE,Bellevue,WA 98008,USA
4,2014-05-02 00:00:00,550000,4.0,2.50,1940,10500,1.0,0,0,4,1140,800,1976,1992,9105 170th Ave NE,Redmond,WA 98052,USA